// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:28b43b4e9d4966d94f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    authDomain: 'bluefarm-96355.firebaseapp.com',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    measurementId: 'G-7E1Y7H769P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvaq9r5eiDZxcsbRk-yjKOPNMm7OE6ko',
    appId: '1:52765421109:android:3ecdbca43237ffa94f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:ee800c1b0b8885724f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    authDomain: 'bluefarm-96355.firebaseapp.com',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    measurementId: 'G-9SC2N9QN9G',
  );
}
