// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:93b3b2a227bc410b4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    authDomain: 'bluefarm-96355.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvaq9r5eiDZxcsbRk-yjKOPNMm7OE6ko',
    appId: '1:52765421109:android:3ecdbca43237ffa94f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    // These IDs are critical for the handoff back to the app
    androidClientId:
        '52765421109-a7mgfjrl3dbjfl17i1v2u8rqdpr1kkq5.apps.googleusercontent.com',
    iosClientId:
        '52765421109-cd5m2ph8br6s5fcudtlo1n4kabikmoh6.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XiT0astzJd7aANXJCmrkU6x1tH7RI9E',
    appId: '1:52765421109:ios:840ff7d9f9f760ec4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    androidClientId:
        '52765421109-a7mgfjrl3dbjfl17i1v2u8rqdpr1kkq5.apps.googleusercontent.com',
    iosClientId:
        '52765421109-jct4tvn8jptmt191m9jbg9nr7kmvf9e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluefarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3XiT0astzJd7aANXJCmrkU6x1tH7RI9E',
    appId: '1:52765421109:ios:840ff7d9f9f760ec4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:3cda898be1ed54bd4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
  );
}
