// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:93b3b2a227bc410b4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    authDomain: 'bluefarm-96355.firebaseapp.com',
    databaseURL: 'https://bluefarm-96355-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    measurementId: 'G-RRYR8MRWBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQvaq9r5eiDZxcsbRk-yjKOPNMm7OE6ko',
    appId: '1:52765421109:android:3ecdbca43237ffa94f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    databaseURL: 'https://bluefarm-96355-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtaLefYYgsGHf7kvLS3N9cNz0fT-k2iSA',
    appId: '1:52765421109:web:3cda898be1ed54bd4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    authDomain: 'bluefarm-96355.firebaseapp.com',
    databaseURL: 'https://bluefarm-96355-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    measurementId: 'G-54W5VSN41M',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3XiT0astzJd7aANXJCmrkU6x1tH7RI9E',
    appId: '1:52765421109:ios:840ff7d9f9f760ec4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    databaseURL: 'https://bluefarm-96355-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    androidClientId: '52765421109-0q90gcfm2o08nefbn7r9tel3fjd30c1l.apps.googleusercontent.com',
    iosClientId: '52765421109-jct4tvn8jptmt191m9jbg9nr7kmvf9e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluefarm',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XiT0astzJd7aANXJCmrkU6x1tH7RI9E',
    appId: '1:52765421109:ios:840ff7d9f9f760ec4f8b7c',
    messagingSenderId: '52765421109',
    projectId: 'bluefarm-96355',
    databaseURL: 'https://bluefarm-96355-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluefarm-96355.firebasestorage.app',
    androidClientId: '52765421109-0q90gcfm2o08nefbn7r9tel3fjd30c1l.apps.googleusercontent.com',
    iosClientId: '52765421109-jct4tvn8jptmt191m9jbg9nr7kmvf9e6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluefarm',
  );
}
